services:
  book_store_api:
    container_name: bookstore_api
    build:
      context: .
      dockerfile: ./book_store/docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./book_store:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/bookstore
    command: >
      uvicorn book_store.app:app --host 0.0.0.0 --port 8000 --reload

  db:
    container_name: bookstore_db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - .db_data:/var/lib/postgresql/data

networks:
  default:
    name: bookstore_network